FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

ENV PYTHONUNBUFFERED 1

# Install tools
# RUN apt-get update && apt-get install -y \
#     git \
#     curl \
#     && rm -rf /var/lib/apt/lists/*

# Install just
# RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

# Create a non-root user
# RUN useradd -m vscode

# USER vscode

# # Install uv
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# WORKDIR /workspaces/events-organizer



